### ISSUE TITLE
Better text editor for posting descriptions/creating topics

### ISSUE THREAD

**Issue by Sabotnik** [FirehoseCommunity/LightningTalkTopics#13]
Ability to do basic bold, italics, etc WYSIWIG editor would be nice

**Comment by Ellcat** [comment]
edit

**Comment by takehiromouri** [comment]
Opened [a PR](https://github.com/FirehoseCommunity/LightningTalkTopics/pull/34) for this :smile:

**Comment by colinrubbert** [comment]
Due to issues with possible code injection and validation, as well as, our lack of need for extensive text input and styling I will be closing this issue. If we want to open a discussion about this we can always reopen the issue request.
