### ISSUE TITLE
No limit to voting

### ISSUE THREAD

**Issue by tylerpendleton** [FirehoseCommunity/LightningTalkTopics#18]
Should authenticate the user before adding a vote.  Then limiting the vote to one per topic.  That way any one person can't decide the flow of the next lightning talks.

**Comment by colinrubbert** [comment]
@tpendleton1693 I'm going to close this issue because it already exists. https://github.com/FirehoseCommunity/LightningTalkTopics/issues/6 

I would like you to post your comment there and your ideas on how we can solve it. I think you're definitely on the right track!
