### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by colinrubbert** [FirehoseCommunity/LightningTalkTopics#2]

**Comment by chaudhary27** [comment]
@colinrubbert I would suggest CodeShip. I experimented with both Travis CI and CodeShip and in my experience CodeShip is easy to integrate and works solid!

**Comment by colinrubbert** [comment]
Is it free? I've used Travis CI, admittedly I didn't set it up but it worked great from my experience. I've never used CodeShip.

**Comment by colinrubbert** [comment]
@chaudhary27 I just looked into it, it is free, should've googled first! Would you want to tackle this together? You said you've set up CodeShip before, correct?

**Comment by chaudhary27** [comment]
UPDATE: scheduled to integrate CI tool on Thursday Sept. 10th after lighting talks!

**Comment by colinrubbert** [comment]
CodeShip has successfully been implemented. Recording of process taken place 2015/9/10 after lightning talks.
