### ISSUE TITLE
Add glyphicons to nav bar

### ISSUE THREAD

**Issue by mkyaw** [FirehoseCommunity/LightningTalkTopics#23]
We can use Bootstrap glyphicons on nav bar

**Comment by jonmast** [comment]
The current navbar icons are glyphicons.

**Comment by colinrubbert** [comment]
@mkyaw did you create this issue after you talked with me? Does it still need to be open since you already solved the issues?

**Comment by mkyaw** [comment]
I actually created the issue before working on it and got right to it. It
has been solved so I think it can be closed. Thanks for checking.

On Sat, Sep 12, 2015 at 6:23 AM, Colin Rubbert notifications@github.com
wrote:

> @mkyaw https://github.com/mkyaw did you create this issue after you
> talked with me? Does it still need to be open since you already solved the
> issues?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FirehoseCommunity/LightningTalkTopics/issues/23#issuecomment-139768810
> .

## 

Cheers,
Myo T Kyaw

**Comment by colinrubbert** [comment]
That's what I thought, I just wanted to be sure.
