### ISSUE TITLE
Use hound to enforce ruby style guide.

### ISSUE THREAD

**Issue by jonmast** [FirehoseCommunity/LightningTalkTopics#25]
houndci.com is a service that will check pull requests to make sure they are following the ruby style guide.

**Comment by kenmazaika** [comment]
HoundCI is pretty cool, but it can trigger dozens GitHub issues on a single pull request.  In my experience it causes so many email from GitHub that I stop looking at the emails.

RuboCop is a better alternative IMO.

**Comment by colinrubbert** [comment]
The only thing I would like about Hound is the automated check part. RuboCop is nice but it's difficult to get people to run it, myself included. Is there a way to automatically run RuboCop before push? I know Hound uses RuboCop to check styling or that's what it looks like. I'd certainly be interested in exploring this deeper.

**Comment by jonmast** [comment]
I would suggest getting an editor plugin to call rubocop. I use Syntastic for vim. But yes, the automated check part is what I thought would be cool. I don't actually have experience with it though and ken's experience sounds pretty bad, so we probably should hold off on this.

**Comment by NehemiahAndrews** [comment]
Apparently you can integrate RuboCop with Codeship so it will trigger a build failure if there are style violations.  

https://intercityup.com/blog/integrate-rubocop-in-your-workflow.html

**Comment by colinrubbert** [comment]
Interesting, I will have to dig into that further. Thanks for the link @NehemiahAndrews.
