### ISSUE TITLE
Adjust CSS Layouts Of Index Cards

### ISSUE THREAD

**Issue by colinrubbert** [FirehoseCommunity/LightningTalkTopics#3]
#### Here is what I think it should look like. If you have other suggested please post and we will discuss them.

![image](https://cloud.githubusercontent.com/assets/10966357/9671954/4982e4b4-525c-11e5-88be-cb8415b94b7a.png)

**Comment by trisalar** [comment]
I'd like to try my hand at this task (in hopes of improving my front-end skills).

**Comment by colinrubbert** [comment]
Seems like an already completed issue. Closing this issue, frontend overhaul has also resolved this issue.
