### ISSUE TITLE
Add a better about page

### ISSUE THREAD

**Issue by MarcoMorawec** [FirehoseCommunity/LightningTalkTopics#41]
The about page is pretty empty right now. 

We should probably add a new about page to the lightningtalks app :)

**Comment by colinrubbert** [comment]
I agree 100%! This would be great low hanging fruit for someone who wants to jump in. A lot of the copy edit that's on the landing page could be repurposed for the the about page quite easily.

**Comment by MarcoMorawec** [comment]
👍 

Also, awesome job on the new design of the lightning talks page!

**Comment by erniejamison** [comment]
Copy edit from the LightningTalkTopics landing page or thefirehoseproject.com? It is under Firehose Project Links.

**Comment by colinrubbert** [comment]
@erniejamison the copy edit can be pulled from the landing page and added to http://firehoselightning.herokuapp.com/about. Maybe not an exact duplicate but most the content is there and can be reused.

**Comment by colinrubbert** [comment]
Thanks @erniejamison for the work!
