### ISSUE TITLE
Bug: Unscheduled and Upcoming Talk Ideas Contains Scheduled Talks

### ISSUE THREAD

**Issue by kenmazaika** [FirehoseCommunity/LightningTalkTopics#5]
These should be filtered out:

![image](https://cloud.githubusercontent.com/assets/233615/9672055/566a754e-5265-11e5-83a4-b8f605df05be.png)

**Comment by colinrubbert** [comment]
Agree 100%, however, I think if we filter them out they may disappear into the nether based on how the code is written. The code will have to be optimized to account for this. 

I can take this on but I would think this would be an awesome opportunity for someone to figure them out. I can help guide anyone who wants to tackle this. There is more than just filtering out the assigned talks (just wanted to give a heads up on this).
