### ISSUE TITLE
Limit 1 Vote Per Person Per Topic

### ISSUE THREAD

**Issue by colinrubbert** [FirehoseCommunity/LightningTalkTopics#6]

**Comment by jonmast** [comment]
How would you propose to implement this? Should we require voters to be logged in, or should we restrict based on ip address/cookie?

**Comment by colinrubbert** [comment]
@tpendleton1693 started looking into this and looks like he started working on a solid way of resolving it. He submitted a PR but needed some refinements, you can take a look [here](https://github.com/FirehoseCommunity/LightningTalkTopics/pull/20).

My personal thought would be people would have to be signed in to vote and the vote would be limited to 1 vote per user, that's the route Tyler went with the it.
